package hieplt.popularmovie.models.orms;

import android.provider.BaseColumns;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.tojc.ormlite.android.annotation.AdditionalAnnotation;

import hieplt.popularmovie.commons.Constants;

/**
 * Created by HiepLT on 11/21/15.
 */
@AdditionalAnnotation.Contract()
@DatabaseTable(tableName = "movies")
@AdditionalAnnotation.DefaultContentUri(authority = Constants.AUTHORITY, path = "movies")
@AdditionalAnnotation.DefaultContentMimeTypeVnd(name = Constants.CONTENT_MINE_TYPE, type = "movies")
public class MovieORM {

    // id is generated by the database and set on the object automagically
    @DatabaseField(columnName = BaseColumns._ID, generatedId = true)
    @AdditionalAnnotation.DefaultSortOrder
    int id;
    @DatabaseField(index = true)
    String title;
    @DatabaseField
    String releaseDate;
    @DatabaseField
    String thumbnailsUrl;
    @DatabaseField
    String voteAverage;
    @DatabaseField
    String plotSynopsis;

    public MovieORM() {}
}
